[build.environment]
GO_VERSION = "1.22.1"
HUGO_VERSION = "0.148.0"
NODE_VERSION = "24.3.0"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = "git config core.quotepath false && hugo --gc --minify"